// layout.tsx
import React from 'react';
import { Toaster } from "@/components/ui/toaster"
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body className="min-h-screen">
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <div className="my-20">
                          <Navbar />
                        </div>
                        <main className="flex-grow flex justify-center max-w-87">
                            {children}
                            <Toaster />
                        </main>
                    </ThemeProvider>
                </body>
            </html>
        </>
    );
};

export default RootLayout;
